src/config/routes.rb
Rails.application.routes.draw do

    # Анализ основных параметров резонатора
    resources :resonators_analyzes do

        get :chart_1_1, on: :collection
        get :chart_1_2, on: :collection
        get :chart_1_3, on: :collection
        get :chart_1_4, on: :collection
        get :chart_1_5, on: :collection

        get :chart_3_1, on: :collection
        get :chart_3_2, on: :collection
        get :chart_3_3, on: :collection
        get :chart_3_4, on: :collection
        get :chart_3_5, on: :collection

        get :chart_5_0, on: :collection
        get :chart_7_0, on: :collection
        get :chart_9_0, on: :collection
        get :chart_11_0, on: :collection

        get :chart_13_0, on: :collection
        get :chart_15_0, on: :collection
        get :chart_17_0, on: :collection
        get :chart_19_0, on: :collection
        get :chart_21_0, on: :collection
        get :chart_23_0, on: :collection
        get :chart_25_0, on: :collection
        get :chart_27_0, on: :collection

    end


    # Анализ брака и отказов
    resources :bad_analyzes do

        # Общая статистика по браку
        get :bad_total, on: :collection

        # Брак на посту ЭВО
        get :bad_evo, on: :collection

        # Брак после ЭВО
        get :bad_after_evo, on: :collection

        # Брак по стадиям производства
        get :bad_stage, on: :collection

        # Общая статистика по отказам
        get :return_total, on: :collection

        # Отказы на посту ЭВО
        get :return_evo, on: :collection

        # Отказы после ЭВО
        get :return_after_evo, on: :collection

        # Отказы по стадиям производства
        get :return_stage, on: :collection

    end

    resources :resonators do

        # Извлечение комплектующих
        get :pull_out_cathode, on: :collection
        get :pull_out_leg, on: :collection
        get :pull_out_fmirror, on: :collection
        get :pull_out_pmirror_1, on: :collection
        get :pull_out_pmirror_2, on: :collection
        get :pull_out_smirror, on: :collection

		get :set_alignment, on: :collection
		get :show_alignment, on: :collection

        get :set_evo, on: :collection
        get :show_evo, on: :collection

        get :set_thermostabilization, on: :collection
        get :show_thermostabilization, on: :collection

        get :set_cold_resistance, on: :collection
        get :show_cold_resistance, on: :collection

        get :set_running_in, on: :collection
        get :show_running_in, on: :collection

        get :set_sealing, on: :collection
        get :show_sealing, on: :collection

        get :set_heat_treatment_in_an_argon_chamber, on: :collection
        get :show_heat_treatment_in_an_argon_chamber, on: :collection

        get :set_varnish_coating, on: :collection
        get :show_varnish_coating, on: :collection

        get :set_metallization_of_mirrors, on: :collection
        get :show_metallization_of_mirrors, on: :collection

        get :set_tinning_mirrors, on: :collection
        get :show_tinning_mirrors, on: :collection

        get :set_test3, on: :collection
        get :show_test3, on: :collection

        get :set_test9, on: :collection
        get :show_test9, on: :collection

        get :set_test10, on: :collection
        get :show_test10, on: :collection

        get :set_control, on: :collection
        get :show_control, on: :collection

        get :search, on: :collection

        # Возврат из не годных
        get :roll_back_bad, on: :collection

    end

    resources :bad_resonators

    resources :sensors do

        # 1
        get :set_align_prisms_and_fpu, on: :collection
        get :show_align_prisms_and_fpu, on: :collection

        # 2
        get :set_checking_the_build_quality_in_screens, on: :collection
        get :show_checking_the_build_quality_in_screens, on: :collection

        # 3
        get :set_check_for_resistance_to_sinusoidal_vibration, on: :collection
        get :show_check_for_resistance_to_sinusoidal_vibration, on: :collection

        # 4
        get :set_check_by_pm, on: :collection
        get :show_check_by_pm, on: :collection

        # 5
        get :set_psi, on: :collection
        get :show_psi, on: :collection

        get :search, on: :collection

        get :ok_sensor_filter, on: :collection

        # Возврат из не годных
        get :roll_back_bad, on: :collection
    end

    resources :bad_sensors

    resources :mirrors do
        get :search, on: :collection
    end

    resources :legs do
        get :search, on: :collection
    end

    resources :cathodes do
        get :search, on: :collection
    end

    devise_for :users

    root "resonators#index"
end

src/app/models/cathode.rb
class Cathode < ApplicationRecord
	resourcify
	# presence - пустое
	# uniqueness - уникально
	validates :number, presence: {message: "Введите номер катода!"}
	validates :date_of_manufacture, presence: {message: "Введите дату изготовления!"}

	# уникально ли сочетание :number и :date_of_manufacture ?
	validates :number, uniqueness: { scope: :date_of_manufacture, message: "Такая запись уже существует!"}

end

src/app/controllers/cathodes_controller.rb
class CathodesController < ApplicationController

	before_action :authenticate_user!
	skip_before_action :authenticate_user!, only:[:index, :search]

    before_action :cathode_list_cols, 
    only: [ :index, :new, :edit, :show, :search ]

    before_action :returns_list_cols,
    only: [ :index, :new, :edit, :search ]

    before_action :element_list_cols,
    only: [ :index, :new, :edit, :search ]

    before_action :parameter_list_cols,
    only: [ :index, :new, :edit, :search ]

    before_action :manufacturer_list_cols,
    only: [ :new, :edit, :search]

    before_action :set_cathode,
    only: [ :edit, :update, :destroy, :show]

    before_action :mode_list_cols,
    only: [ :new, :edit, :search]

	def index
        # Текущая страница
        if $cc_page == nil
            $cc_page = 1
        end

        if params[:page]
            $cc_page = params[:page]
        end

        @cathodes = Cathode.order(created_at: :desc).page($cc_page).per_page(25)
	end

    def search
        @search_val = params[:search_val]
        if @search_val
            @cathodes = Cathode.where("number LIKE ?", "%#{@search_val}%").order(number: :desc).page(params[:page]).per_page(25)
        end
    end

	def new
		@cathode = Cathode.new
	end

	def create
		@cathode = Cathode.new(cathode_params)
		if @cathode.save
			redirect_to cathodes_path,
			notice: "Добавлена запись #{@cathode.number}"
		else
			redirect_to new_cathode_path,
			notice: @cathode.errors.first[1]
		end
	end

	def edit
	end

	def update
		update_params = cathode_params 
		
		if update_params[:the_result_of_cathode_manufacturing] == 'Годен'
			update_params[:reason_for_rejection] = nil
		end

		if @cathode.update(update_params)
			redirect_to cathodes_path,
			notice: "Запись #{@cathode.number} изменена"
		else
			redirect_to edit_cathode_path,
			notice: @cathode.errors.first[1]
		end
	end

	def destroy
		del_cathode_from_resonator(@cathode.resonator_id)
		if @cathode.destroy
			redirect_to cathodes_path,
			notice: "Удалена запись #{@cathode.number}"
		else
			redirect_to cathodes_path,
			notice: "Не удалось удалить запись #{@cathode.number}"
		end
	end

	def show
	end

    private

    def set_cathode
        @cathode = Cathode.find(params[:id])
    end

    def del_cathode_from_resonator(id)
    	if resonator_id = @cathode.resonator_id
			resonator = Resonator.find(resonator_id)
			resonator.update cathode_id: nil
		end
    end


    def cathode_params
        params.require(:cathode).permit(
			:number,
			:date_of_manufacture,
			:manufacturer_supplier,
			:result_of_manufacturing_the_workpiece,
			:description_of_appearance,
			:oxidation_date,
			:oxidation_mode,
			:breakdown_voltage,
			:combustion_voltage,
			:tb_first_inclusion,
			:tb_subsequent_inclusions,
			:date_of_transfer_to_assembly_otk,
			:the_result_of_cathode_manufacturing,
			:reason_for_rejection,
			:date_of_transfer_to_assembly,
			:deviations,
			:resonator_id,
			:date_of_installation_in_the_resonator)





    end
end

src/app/helpers/cathodes_helper.rb
module CathodesHelper
end

src/app/views/cathodes/_cathodes.html.slim
. align="left" = will_paginate @cathodes, previous_label: "<", next_label: ">"

table.table.table-condensed style="width: 90%" align="center"
	thead
		tr
			th.center = @cathode_title[0]
			th.center = @cathode_title[12]
			th.center = @cathode_title[2]
			th.center = @cathode_title[15]
			th.center = @cathode_title[17]
			th.center = @cathode_title[18]
			th.center = @cathode_title[19]
			th.center = @cathode_title[20]
			th colspan=3

	tbody
		- @cathodes.each do |cathode|
			- @ctd_title = ""

			tr
				td.center = cathode.number
				td.center = cathode.date_of_transfer_to_assembly_otk
				td.center = cathode.manufacturer_supplier
				td.center = cathode.date_of_transfer_to_assembly

				td.center
					- if cathode.resonator_id?
						- resonator = Resonator.find(cathode.resonator_id)
						= link_to "#{resonator.number}", resonator
						td.center = cathode.date_of_installation_in_the_resonator
					-else
						td

				-if cathode.result_of_manufacturing_the_workpiece == 'Не годен' or cathode.reason_for_rejection?
					td.center.back_error Не годен
				- else
					td.center.success Годен

				td.center title="#{cathode.deviations}"
					- if cathode.deviations?
						= link_to content_tag('span', '', class: 'fa fa-file-o'),cathode_path(cathode) + '#deviations', class: 'action'

				td.center = link_to content_tag('span', '', class: 'fa fa-circle-o'), cathode_path(cathode), class: 'action'

				-if user_signed_in?
					-if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :cathode
						td.center = link_to content_tag('span', '', class: 'fa fa-pencil'), edit_cathode_path(cathode), class: 'action'

				-if user_signed_in?
					-if current_user.has_role? :admin or current_user.has_role? :moderator
						td.center = link_to content_tag('span', '', class: 'fa fa-trash'), cathode, class: 'action', data: {confirm: "Хотите удалить катод #{cathode.number}?"}, method: :delete

src/app/views/cathodes/_form.html.slim
= form_for @cathode do |f|
	table.table-condensed
		/ Номер катода
		tr
			td = @cathode_title[0]
			td = f.text_field :number, class: 'form-control'

		/ Дата изготовления заготовки
		tr
			td = @cathode_title[1]
			td = f.date_select :date_of_manufacture, {include_blank: true}

		/ Изготовитель (поставщик)
		tr
			td = @cathode_title[2]
			td = f.select :manufacturer_supplier, @manufacturer_list, {}, {class: 'select2_nosearch form-control', disabled: false}

		/ Результат изготовления заготовки
		tr
			td = @cathode_title[3]
			td = f.select :result_of_manufacturing_the_workpiece, [["Годен"],["Не годен"]], {}, {class: 'select2_nosearch form-control', disabled: false}

		/ Описание внешнего вида
		tr
			td = @cathode_title[4]
			td = f.text_area :description_of_appearance, class: 'form-control'

		/ Дата окисления (отпай с поста окисления)
		tr
			td = @cathode_title[5]
			td = f.date_select :oxidation_date, {include_blank: true}

		/ Режим окисления
		tr
			td = @cathode_title[6]
			td = f.select :oxidation_mode, @mode_list, {}, {class: 'select2_nosearch form-control', disabled: false}

		/ Напряжение пробоя
		tr
			td = @cathode_title[7]
			td = f.number_field :breakdown_voltage, class: 'form-control'

		/ Напряжение горения
		tr
			td = @cathode_title[8]
			td = f.number_field :combustion_voltage, class: 'form-control'

		/-----------------------------
		tr
			td colspan=2
				hr

		/ Время пробоя
		tr
			td 
				b = @cathode_title[9] 

		/ Первое включение
		tr
			td = @cathode_title[10]
			td = f.number_field :tb_first_inclusion, class: 'form-control'

		/ Последующие включения(max)
		tr
			td = @cathode_title[11]
			td = f.number_field :tb_subsequent_inclusions, class: 'form-control'

		/-----------------------------
		tr
			td colspan=2
				hr

		/ Дата сдачи в ОТК
		tr
			td = @cathode_title[12]
			td = f.date_select :date_of_transfer_to_assembly_otk, {include_blank: true}

		/ Результат изготовления катода
		tr
			td = @cathode_title[13]
			td = f.select :the_result_of_cathode_manufacturing, [["Годен"],["Не годен"]], {}, {id: 'the_result_of_cathode_manufacturing_field', class: 'select2_nosearch form-control', disabled: false}


		/ Причина забракования
		tr
			td = @cathode_title[14]
			td data-toggle="tooltip" data-placement="right" title="Введите или выберите из списка"
				= f.select :reason_for_rejection, [["Внешний вид"],["Время пробоя"],@cathode.reason_for_rejection], {}, {id: 'reason_for_rejection_field', class: 'select2_tags form-control', disabled: true}

		/ Дата передачи на сборку
		tr
			td = @cathode_title[15]
			td = f.date_select :date_of_transfer_to_assembly, {include_blank: true}

		/ Отклонения (по картам отклонений)
		tr
			td = @cathode_title[16]
			td = f.text_field :deviations, class: 'form-control'

		/-------------------------------------------------------------------------------------------
        tr
            td colspan=2
                hr
		tr
			td align="center" colspan="3" = f.submit "Внести", class: 'btn btn-default'
				

src/app/views/cathodes/edit.html.slim
div.container-fluid
    p.sys_error
        = notice
    div.row
        div.col-sm-1
			h4 = "Редактировать катод #{@cathode.number}"
			= link_to "Назад", cathodes_path, class: 'btn btn-default'

        div.col-sm-11
            = render 'form'

src/app/views/cathodes/index.html.slim
div.container-fluid
    p.sys_success
        = notice
    div.row
        div.col-sm-1
			h4 Катоды
				
			-if user_signed_in?
				-if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :cathode
					= link_to "Внести", new_cathode_path, class: 'btn btn-default'

            hr

            = form_tag('cathodes/search', method: 'get', id: 'cathodes_search_form') do
                table
                    tr
                        td = text_field_tag :search_val, '', class: 'form-control'
                        td 
                            .btn.fa.fa-search onclick="$('#cathodes_search_form').submit()" = submit_tag nil, style: 'display: none;'

        div.col-sm-11
            = render 'cathodes'

src/app/views/cathodes/new.html.slim
div.container-fluid
    p.sys_error
        = notice
    div.row
        div.col-sm-1
            h4 = "Внести катод"
            = link_to "Назад", cathodes_path, class: 'btn btn-default'

        div.col-sm-11
            = render 'form'

src/app/views/cathodes/search.html.slim
div.container-fluid
    p.sys_success
        = notice
    div.row
        div.col-sm-1
			h4 Катоды
			= link_to "Назад", cathodes_path, class: 'btn btn-default'

            hr

			span ="Результат поиска по #{@search_val}"
		div.col-sm-11
			= render 'cathodes'

src/app/views/cathodes/show.html.slim
div.container-fluid
    p.sys_error
        = notice
    div.row
        div.col-sm-1
			h4 = "Катод #{@cathode.number}"
			= link_to "Назад", cathodes_path, class: 'btn btn-default'

        div.col-sm-11
        	table.table-condensed

				tr
					td = @cathode_title[0]
					td = @cathode.number
				tr
					td = @cathode_title[1]
					td = @cathode.date_of_manufacture
				tr
					td = @cathode_title[2]
					td = @cathode.manufacturer_supplier
				tr
					td = @cathode_title[3]
					td = @cathode.result_of_manufacturing_the_workpiece
				tr
					td = @cathode_title[4]
					td = @cathode.description_of_appearance
				tr
					td = @cathode_title[5]
					td = @cathode.oxidation_date
				tr
					td = @cathode_title[6]
					td = @cathode.oxidation_mode
				tr
					td = @cathode_title[7]
					td = @cathode.breakdown_voltage
				tr
					td = @cathode_title[8]
					td = @cathode.combustion_voltage
				
				tr
					td colspan=2
						hr
				tr
					td 
						b = @cathode_title[9]
					td
				tr
					td = @cathode_title[10]
					td = @cathode.tb_first_inclusion
				tr
					td = @cathode_title[11]
					td = @cathode.tb_subsequent_inclusions

				tr
					td colspan=2
						hr

				tr
					td = @cathode_title[12]
					td = @cathode.date_of_transfer_to_assembly_otk
				tr
					td = @cathode_title[13]
					td = @cathode.the_result_of_cathode_manufacturing
				tr
					td = @cathode_title[14]
					td = @cathode.reason_for_rejection
				tr
					td = @cathode_title[15]
					td = @cathode.date_of_transfer_to_assembly
				tr id="deviations"
					td = @cathode_title[16]
					td = @cathode.deviations
				
				- if @cathode.resonator_id?
                    tr
                        td colspan=2
                            hr
					tr
						td = @cathode_title[17]
                        td = link_to "#{Resonator.find(@cathode.resonator_id).number}", resonators_path

                    tr
                    	td = @cathode_title[18]
                    	td = @cathode.date_of_installation_in_the_resonator


						