src/config/routes.rb
Rails.application.routes.draw do

    # Анализ основных параметров резонатора
    resources :resonators_analyzes do

        get :chart_1_1, on: :collection
        get :chart_1_2, on: :collection
        get :chart_1_3, on: :collection
        get :chart_1_4, on: :collection
        get :chart_1_5, on: :collection

        get :chart_3_1, on: :collection
        get :chart_3_2, on: :collection
        get :chart_3_3, on: :collection
        get :chart_3_4, on: :collection
        get :chart_3_5, on: :collection

        get :chart_5_0, on: :collection
        get :chart_7_0, on: :collection
        get :chart_9_0, on: :collection
        get :chart_11_0, on: :collection

        get :chart_13_0, on: :collection
        get :chart_15_0, on: :collection
        get :chart_17_0, on: :collection
        get :chart_19_0, on: :collection
        get :chart_21_0, on: :collection
        get :chart_23_0, on: :collection
        get :chart_25_0, on: :collection
        get :chart_27_0, on: :collection

    end


    # Анализ брака и отказов
    resources :bad_analyzes do

        # Общая статистика по браку
        get :bad_total, on: :collection

        # Брак на посту ЭВО
        get :bad_evo, on: :collection

        # Брак после ЭВО
        get :bad_after_evo, on: :collection

        # Брак по стадиям производства
        get :bad_stage, on: :collection

        # Общая статистика по отказам
        get :return_total, on: :collection

        # Отказы на посту ЭВО
        get :return_evo, on: :collection

        # Отказы после ЭВО
        get :return_after_evo, on: :collection

        # Отказы по стадиям производства
        get :return_stage, on: :collection

    end

    resources :resonators do

        # Извлечение комплектующих
        get :pull_out_cathode, on: :collection
        get :pull_out_leg, on: :collection
        get :pull_out_fmirror, on: :collection
        get :pull_out_pmirror_1, on: :collection
        get :pull_out_pmirror_2, on: :collection
        get :pull_out_smirror, on: :collection

		get :set_alignment, on: :collection
		get :show_alignment, on: :collection

        get :set_evo, on: :collection
        get :show_evo, on: :collection

        get :set_thermostabilization, on: :collection
        get :show_thermostabilization, on: :collection

        get :set_cold_resistance, on: :collection
        get :show_cold_resistance, on: :collection

        get :set_running_in, on: :collection
        get :show_running_in, on: :collection

        get :set_sealing, on: :collection
        get :show_sealing, on: :collection

        get :set_heat_treatment_in_an_argon_chamber, on: :collection
        get :show_heat_treatment_in_an_argon_chamber, on: :collection

        get :set_varnish_coating, on: :collection
        get :show_varnish_coating, on: :collection

        get :set_metallization_of_mirrors, on: :collection
        get :show_metallization_of_mirrors, on: :collection

        get :set_tinning_mirrors, on: :collection
        get :show_tinning_mirrors, on: :collection

        get :set_test3, on: :collection
        get :show_test3, on: :collection

        get :set_test9, on: :collection
        get :show_test9, on: :collection

        get :set_test10, on: :collection
        get :show_test10, on: :collection

        get :set_control, on: :collection
        get :show_control, on: :collection

        get :search, on: :collection

        # Возврат из не годных
        get :roll_back_bad, on: :collection

    end

    resources :bad_resonators

    resources :sensors do

        # 1
        get :set_align_prisms_and_fpu, on: :collection
        get :show_align_prisms_and_fpu, on: :collection

        # 2
        get :set_checking_the_build_quality_in_screens, on: :collection
        get :show_checking_the_build_quality_in_screens, on: :collection

        # 3
        get :set_check_for_resistance_to_sinusoidal_vibration, on: :collection
        get :show_check_for_resistance_to_sinusoidal_vibration, on: :collection

        # 4
        get :set_check_by_pm, on: :collection
        get :show_check_by_pm, on: :collection

        # 5
        get :set_psi, on: :collection
        get :show_psi, on: :collection

        get :search, on: :collection

        get :ok_sensor_filter, on: :collection

        # Возврат из не годных
        get :roll_back_bad, on: :collection
    end

    resources :bad_sensors

    resources :mirrors do
        get :search, on: :collection
    end

    resources :legs do
        get :search, on: :collection
    end

    resources :cathodes do
        get :search, on: :collection
    end

    devise_for :users

    root "resonators#index"
end

src/app/models/sensor.rb
class Sensor < ApplicationRecord
	resourcify
	# presence - пустое
	# uniqueness - уникально
	validates :number, presence: {message: "Введите номер датчика!"}
	validates :number, uniqueness: {message: "Датчик с таким номером уже внесен в базу!"}
	validates :resonator_id, presence: {message: "Введите номер резонатора!"}
end

src/app/controllers/sensors_controller.rb
class SensorsController < ApplicationController

	before_action :authenticate_user!
	skip_before_action :authenticate_user!, only: [:index, :show,
		:show_coil_winding, :show_align_prisms_and_fpu,
		:show_assembly_and_wiring, :show_checking_the_build_quality_in_screens,
		:show_check_for_resistance_to_sinusoidal_vibration, :show_psi, :search ]

	before_action :set_step,
	only: [
		:set_align_prisms_and_fpu,
		:set_checking_the_build_quality_in_screens,
		:set_check_for_resistance_to_sinusoidal_vibration,
		:set_psi ]

	before_action :sensor_list_cols,
	only: [
		:search, :ok_sensor_filter,
		:index, :new, :edit, :show,
		:set_align_prisms_and_fpu, :show_align_prisms_and_fpu,
		:set_checking_the_build_quality_in_screens, :show_checking_the_build_quality_in_screens,
		:set_check_for_resistance_to_sinusoidal_vibration, :show_check_for_resistance_to_sinusoidal_vibration,
		:set_check_by_pm, :show_check_by_pm,
		:set_psi, :show_psi ]

	before_action :set_sensor,
	only: [
		:show, :edit, :update, :destroy,
		:set_align_prisms_and_fpu, :show_align_prisms_and_fpu,
		:set_checking_the_build_quality_in_screens, :show_checking_the_build_quality_in_screens,
		:set_check_for_resistance_to_sinusoidal_vibration, :show_check_for_resistance_to_sinusoidal_vibration,
		:set_check_by_pm, :show_check_by_pm,
		:set_psi, :show_psi ]

	before_action :returns_list_cols,
	only: [
		:show,
		:search, :ok_sensor_filter,
		:set_align_prisms_and_fpu, :show_align_prisms_and_fpu,
		:set_checking_the_build_quality_in_screens, :show_checking_the_build_quality_in_screens,
		:set_check_for_resistance_to_sinusoidal_vibration, :show_check_for_resistance_to_sinusoidal_vibration,
		:set_check_by_pm, :show_check_by_pm,
		:set_psi, :show_psi	]

	before_action :element_list_cols,
	only: [
		:search, :ok_sensor_filter,
		:set_align_prisms_and_fpu, :show_align_prisms_and_fpu,
		:set_checking_the_build_quality_in_screens, :show_checking_the_build_quality_in_screens,
		:set_check_for_resistance_to_sinusoidal_vibration, :show_check_for_resistance_to_sinusoidal_vibration,
		:set_check_by_pm, :show_check_by_pm,
		:set_psi, :show_psi ]

	before_action :parameter_list_cols,
	only: [
		:search, :ok_sensor_filter,
		:set_align_prisms_and_fpu, :show_align_prisms_and_fpu,
		:set_checking_the_build_quality_in_screens, :show_checking_the_build_quality_in_screens,
		:set_check_for_resistance_to_sinusoidal_vibration, :show_check_for_resistance_to_sinusoidal_vibration,
		:set_check_by_pm, :show_check_by_pm,
		:set_psi, :show_psi ]

	# Возврат из не годных.
	# Пока убрал ибо валидация не пропускает создание записи без прикрепленного резонатора
	def roll_back_bad
		if BadSensor.where params[:id]
			@bad_sensor = BadSensor.find(params[:id])

			if @bad_sensor.ap_result == 'Возврат'
				@bad_sensor.update ap_result: nil
				@bad_sensor.update ap_return_date: nil
				@bad_sensor.update ap_reason_for_return: nil
				@bad_sensor.update ap_for_the_return_list: nil
				@bad_sensor.update ap_refund_description: nil
			end

			if @bad_sensor.cb_result == 'Возврат'
				@bad_sensor.update cb_result: nil
				@bad_sensor.update cb_return_date: nil
				@bad_sensor.update cb_reason_for_return: nil
				@bad_sensor.update cb_for_the_return_list: nil
				@bad_sensor.update cb_refund_description: nil
			end

			if @bad_sensor.cf_result == 'Возврат'
				@bad_sensor.update cf_result: nil
				@bad_sensor.update cf_return_date: nil
				@bad_sensor.update cf_reason_for_return: nil
				@bad_sensor.update cf_for_the_return_list: nil
				@bad_sensor.update cf_refund_description: nil
			end

			if @bad_sensor.cp_result == 'Возврат'
				@bad_sensor.update cp_result: nil
				@bad_sensor.update cp_return_date: nil
				@bad_sensor.update cp_reason_for_return: nil
				@bad_sensor.update cp_for_the_return_list: nil
				@bad_sensor.update cp_refund_description: nil
			end

			if @bad_sensor.ps_result == 'Возврат' or
				@bad_sensor.update ps_result: nil
				@bad_sensor.update ps_return_date: nil
				@bad_sensor.update ps_reason_for_return: nil
				@bad_sensor.update ps_for_the_return_list: nil
				@bad_sensor.update ps_refund_description: nil
			end

		end

		# Далее переместим запись из не годных в годные

		# Создаю запись в таблице нормальных датчиков
		@sensor = Sensor.create(@bad_sensor.attributes)
		@bad_sensor.destroy

		set_history("Возвращено из брака")

		redirect_to sensors_path

	end

	def search
		@search_val = params[:search_val]
		if Sensor.where("number LIKE ?", "%#{@search_val}%")
			@sensors = Sensor.where("number LIKE ?", "%#{@search_val}%")
		end

		if BadSensor.where("number LIKE ?", "%#{@search_val}%")
			@bad_sensors = BadSensor.where("number LIKE ?", "%#{@search_val}%")
		end
	end

	def ok_sensor_filter
		@date = Date.civil(params[:date][:year].to_i, params[:date][:month].to_i)
		@date_interval = @date .. @date + (1.month - 1.day)
		@sensors = Sensor.where(psi: 'Завершена').where(ps_date_of_psi: @date_interval).order(ps_date_of_psi: :desc).page(params[:page]).per_page(20)
	end

	def index
		@work_sensor = Sensor.where.not(suitable: true)
		@good_sensor = Sensor.where(suitable: true)
		@current_title = "В производстве"
		$rv_type = true

		case params[:view_type]
		when 'good'
			@sensors = @good_sensor.order(created_at: :desc).page(params[:page]).per_page(20)
			@current_title = "Годные"
			$rv_type = true

		when 'bad'
			@sensors = BadSensor.all.order(created_at: :desc).page(params[:page]).per_page(20)
			@current_title = "Не годные"
			$rv_type = false
		else
			@sensors = @work_sensor.order(created_at: :desc).page(params[:page]).per_page(999)
		end

		respond_to do |format|
			format.html
			#format.csv { send_data @sensors.to_csv }
			#format.xls # { send_data @sensors.to_csv(col_sep: "\t") }
		end
	end

	def new
		@sensor = Sensor.new
	end

	def create
		@sensor = Sensor.new(sensor_params)

		if @sensor.save
			end_count(@sensor)

			# Установить связь с резонатором
			if @sensor.resonator_id?
				set_sensor_in_resonator(@sensor)
			end


			set_history("Запись создана")

			redirect_to @sensor,
			notice: "Добавлена запись #{@sensor.number}"
		else
			redirect_to new_sensor_path,
			notice: @sensor.errors.first[1]
		end
	end

	def edit
	end

	def show
		@histories = History.where(dev_id: @sensor.id)
	end

	def update

		if @sensor.update(sensor_params)

			end_count(@sensor)

			if @sensor.resonator_id?
				set_sensor_in_resonator(@sensor)
			end

			check_the_status_of_marriage(@sensor)

			set_history("Сведения обновлены")

			redirect_to sensor_path,
            notice: "Запись #{@sensor.number} изменена"
		else
			redirect_to edit_sensor_path,
			notice: @sensor.errors.first[1]
		end
	end

	def destroy
		del_sensor_from_resonator(@sensor)

		# Удаляю историю
		if History.where dev_id: @sensor.id
			@history = History.where dev_id: @sensor.id

			@history.each do |h|
				h.destroy
			end
		end

		if @sensor.destroy
			redirect_to sensors_path,
            notice: "Удалена запись #{@sensor.number}"
		else
			redirect_to sensors_path,
            notice: "Не удалось удалить запись #{@sensor.number}"
		end
	end

	private

		def end_count(sensor)

			count = 0

			if sensor.align_prisms_and_fpu == 'Завершена'
			    count += 1
			end

			if sensor.checking_the_build_quality_in_screens == 'Завершена'
			    count += 1
			end

			if sensor.check_for_resistance_to_sinusoidal_vibration == 'Завершена'
			    count += 1
			end

			if sensor.check_by_pm == 'Завершена'
			    count += 1
			end

			if sensor.psi == 'Завершена'
			    count += 1
			end

			sensor.update end_count: count

			if count == 5
			    sensor.update suitable: true
			else
			    sensor.update suitable: false
			end

		end

		# Проверка стаутса брака
		def check_the_status_of_marriage(sensor)

			if 	sensor.ap_result == 'Возврат' or
        		sensor.cb_result == 'Возврат' or
        		sensor.cf_result == 'Возврат' or
        		sensor.cp_result == 'Возврат' or
        		sensor.ps_result == 'Возврат'

				if Resonator.find_by id: sensor.resonator_id

					# Убираем иформацию о датчике из резонатора
					resonator = Resonator.find(sensor.resonator_id)
					resonator.update sensor_id: nil

					# Убираем информацию о резонаторе из датчика
					sensor.update resonator_id: nil

				end

				# Создаю запись в таблице испорченных резонаторов
				bad_sensor = BadSensor.create(sensor.attributes)
				set_history("Направлено в брак")

				# Удаляю текущую запись из таблицы годных резонаторов
				sensor.destroy

				sensor = bad_sensor

			end
		end

		# Записать в историю
		def set_history(operation)
			History.create(dev: 'sensor', dev_id: @sensor.id, operation: operation, operator: 'noname')
		end

		def set_sensor
			if Sensor.find_by(id: params[:id])
				@sensor = Sensor.find(params[:id])
			elsif BadSensor.find_by(id: params[:id])
				@sensor = BadSensor.find(params[:id])
			else
				@sensor = Sensor.last
		end


		end

		def set_sensor_in_resonator(sensor)
			if Resonator.find_by id: sensor.resonator_id
				resonator = Resonator.find(sensor.resonator_id)
				resonator.update sensor_id: sensor.id
			end
		end


		# Удаление информации о датчике из резонатора
		def del_sensor_from_resonator(sensor)
			if Resonator.find_by id: sensor.resonator_id
				resonator = Resonator.find(sensor.resonator_id)
				resonator.update sensor_id: nil
			end
		end

		def sensor_params
			params.require(:sensor).permit(
			:number,
			:resonator_id,
			:date_of_manufacture_of_the_resonator,

			:align_prisms_and_fpu,
			:ap_date,
			:ap_the_combustion_voltage_in_2_sec,
			:ap_the_combustion_voltage_after_35_sec,
			:ap_the_combustion_voltage_after_10_min,
			:ap_the_transmission_coefficient_pb1,
			:ap_the_transmission_coefficient_pb2,
			:ap_result,
			:ap_return_date,
			:ap_reason_for_return,
			:ap_for_the_return_list,
			:ap_refund_description,

			:checking_the_build_quality_in_screens,
			:cb_date,
			:cb_the_combustion_voltage_in_2_sec,
			:cb_the_combustion_voltage_after_35_sec,
			:cb_the_combustion_voltage_after_10_min,

src/app/helpers/sensors_helper.rb
module SensorsHelper
end

src/app/views/sensors/_align_prisms_and_fpu_show.html.slim
.
	/ Дата юстировки призмы и ФПУ
	.row
		.col-sm-7
			= @sensor_ap_title[1]
		.col-sm-5
			 = @sensor.ap_date

 	/ Напряжение горения через 2сек, U(2с)гор, В
	.row
		.col-sm-7
			= @sensor_ap_title[2]
		.col-sm-5
			= @sensor.ap_the_combustion_voltage_in_2_sec

	/ Напряжение горения через 35сек, U(35с)гор, В
	.row
		.col-sm-7
			= @sensor_ap_title[3]
		.col-sm-5
			= @sensor.ap_the_combustion_voltage_after_35_sec

	/ Напряжение горения через 10 мин, U(10м)гор, В
	.row
		.col-sm-7
			= @sensor_ap_title[4]
		.col-sm-5
			= @sensor.ap_the_combustion_voltage_after_10_min

	/ Коэффициент передачи ПБ1, Uλпб1, В
	.row
		.col-sm-7
			= @sensor_ap_title[5]
		.col-sm-5
			= @sensor.ap_the_transmission_coefficient_pb1

	/ Коэффициент передачи ПБ2, Uλпб2, В
	.row
		.col-sm-7
			= @sensor_ap_title[6]
		.col-sm-5
			= @sensor.ap_the_transmission_coefficient_pb2

	.row
		.col-sm-12
			hr

	/ Результат
	.row
		.col-sm-7
			= @return_title[0]
		.col-sm-5
			= @sensor.ap_result

	- if @sensor.ap_reason_for_return? and @align_prisms_and_fpu_return_list.rassoc(@sensor.ap_reason_for_return)

		/ Дата
		.row
			.col-sm-7
				= @return_title[1]
			.col-sm-5
				= @sensor.ap_return_date
		/ Причина возврата
		.row
			.col-sm-7
				= @return_title[2]
			.col-sm-5
				= "#{@align_prisms_and_fpu_return_list.rassoc(@sensor.ap_reason_for_return).first}(#{@sensor.ap_for_the_return_list})"
		/ Описание возврата
		.row
			.col-sm-7
				= @return_title[3]
			.col-sm-5
				= @sensor.ap_refund_description

src/app/views/sensors/_check_by_pm_show.html.slim
/ Дата проведения
.row
    .col-sm-7
        = @sensor_cp_title[1]
    .col-sm-5
        = @sensor.cp_date

.row
    .col-sm-12
        hr

/ Результат
.row
    .col-sm-7
        = @return_title[0]
    .col-sm-5
        = @sensor.cp_result

- if @sensor.cp_reason_for_return? and @check_by_pm_return_list.rassoc(@sensor.cp_reason_for_return)
    / Дата
    .row
        .col-sm-7
            = @return_title[1]
        .col-sm-5
            = @sensor.cp_return_date

    / Причина возврата
    .row
        .col-sm-7
            = @return_title[2]
        .col-sm-5
            = "#{@check_by_pm_return_list.rassoc(@sensor.cp_reason_for_return).first}(#{@sensor.cp_for_the_return_list})"

    / Описание
    .row
        .col-sm-7
            = @return_title[3]
        .col-sm-5
            = @sensor.cp_refund_description

src/app/views/sensors/_check_for_resistance_to_sinusoidal_vibration_form.html.slim
= form_for @sensor do |f|

    / Дата проведения
    .row
        .col-sm-7
			= @sensor_cf_title[1]
        .col-sm-5
			= f.text_field :cf_date,
            { include_blank: true,
            class: 'datepicker form-control' }

    .row
        .col-sm-12
            hr

    / Результат
    .row
        .col-sm-7
              = @return_title[0]
        .col-sm-5
            = f.select :cf_result,
            [ ["Годен"], ["Возврат"] ], {},
            { id: 'result_field',
            class: 'select2_nosearch form-control',
            style: 'width: 100%;' }


    .return_fields
        / Дата возврата
        .row
            .col-sm-7
                  = @return_title[1]
            .col-sm-5
                = f.text_field :cf_return_date,
                { include_blank: true,
                class: 'form-control datepicker',
                id: 'return_date_field',
                value: Date.today }


        / Причина возврата
        .row
            .col-sm-7
                = @return_title[2]
            .col-sm-5
                - return_list = @check_for_resistance_to_sinusoidal_vibration_return_list.values_at(0, 6, 12)
                = f.select :cf_reason_for_return,
                return_list, {},
                { id: 'reason_for_return_field',
                class: 'select2_nosearch form-control',
                style: 'width: 100%;' }

        .row
            .col-sm-7
            .col-sm-5
                .option-group-0 {
                data-toggle = "tooltip"
                data-placement = "right"
                title = "Выберите" }
                    = f.select :cf_for_the_return_list,
                    @check_for_resistance_to_sinusoidal_vibration_return_list[1..5], {},
                    { id: 'option-group-0-field',
                    class: 'select2_nosearch form-control',
                    style: 'width: 100%;' }

                .option-group-1 {
                data-toggle = "tooltip"
                data-placement = "right"
                title = "Выберите" }
                    = f.select :cf_for_the_return_list,
                    @check_for_resistance_to_sinusoidal_vibration_return_list[7..11], {},
                    { id: 'option-group-1-field',
                    class: 'select2_nosearch form-control',
                    style: 'width: 100%;' }

                .option-other {
                data-toggle = "tooltip"
                data-placement = "right"
                title = "Введите с клавиатуры" }
                    = f.text_field :cf_for_the_return_list,
                    { id: 'option-other-field',
                    class: 'form-control' }

        .row
            .col-sm-7
                = @return_title[3]
            .col-sm-5
                = f.text_area :cf_refund_description,
                { id: 'return_description_field',
                class: 'form-control' }

    .row
        .col-sm-12
            hr

    .row
        .col-sm-7
            = @status_title
        .col-sm-5
            = f.select :check_for_resistance_to_sinusoidal_vibration,
            [ ["Не завершена"],["Завершена"] ], {},
            { class: 'select2_nosearch form-control' }

    .row
        .col-sm-12
            hr

    / Внести
    .row
        .col-sm-10
        .col-sm-2
            = f.submit "Внести",
            { class: 'btn btn-default form-control' }

src/app/views/sensors/_check_for_resistance_to_sinusoidal_vibration_show.html.slim
/ Дата проведения
.row
	.col-sm-7
		= @sensor_cf_title[1]
	.col-sm-5
		= @sensor.cf_date

.row
	.col-sm-12
		hr

/ Результат
.row
	.col-sm-7
		= @return_title[0]
	.col-sm-5
		= @sensor.cf_result

-if @sensor.cf_reason_for_return? and @check_for_resistance_to_sinusoidal_vibration_return_list.rassoc(@sensor.cf_reason_for_return)

	/ Дата
	.row
		.col-sm-7
			= @return_title[1]
		.col-sm-5
			= @sensor.cf_return_date

	/ Причина возврата
	.row
		.col-sm-7
			= @return_title[2]
		.col-sm-5
			= "#{@check_for_resistance_to_sinusoidal_vibration_return_list.rassoc(@sensor.cf_reason_for_return).first}(#{@sensor.cf_for_the_return_list})"

	/ Описание возврата
	.row
		.col-sm-7
			= @return_title[3]
		.col-sm-5
			= @sensor.cf_refund_description

src/app/views/sensors/_psi_show.html.slim
/ Дата проведения
.row
	.col-sm-7
		= @sensor_ps_title[1]
	.col-sm-5
		= @sensor.ps_date

/ Амплитуда выходного сигнала 1 на рабочей моде, АВ1, В
.row
	.col-sm-7
		= @sensor_ps_title[3]
	.col-sm-5
		= @sensor.ps_the_amplitude_of_the_output_signal_1_in_the_working_mode

/ Амплитуда выходного сигнала 2 на рабочей моде, АВ2, В
.row
	.col-sm-7
		= @sensor_ps_title[2]
	.col-sm-5
		= @sensor.ps_the_amplitude_of_the_output_signal_2_in_the_operating_mode

/ Коэффициент передачи НУ на рабочей моде, Кну, КГц/А
.row
	.col-sm-7
		= @sensor_ps_title[4]
	.col-sm-5
		= @sensor.ps_the_transmission_coefficient_of_the_ou_in_the_working_mode

/ Напряжение горения
.row
	.col-sm-7
		= @sensor_ps_title[5]
	.col-sm-5
		= @sensor.ps_combustion_voltage
.row
	.col-sm-12
		hr

/ Результат
.row
	.col-sm-7
		= @return_title[0]
	.col-sm-5
		= @sensor.ps_result

- if @sensor.ps_reason_for_return? and @psi_return_list.rassoc(@sensor.ps_reason_for_return)
	/ Дата
	.row
		.col-sm-7
			= @return_title[1]
		.col-sm-5
			= @sensor.ps_return_date

	/ Причина возврата
	.row
		.col-sm-7
			= @return_title[2]
		.col-sm-5
			= "#{@psi_return_list.rassoc(@sensor.ps_reason_for_return).first}(#{@sensor.ps_for_the_return_list})"

	/ Описание
	.row
		.col-sm-7
			= @return_title[3]
		.col-sm-5
			= @sensor.ps_refund_description

src/app/views/sensors/edit.html.slim
.container-fluid

	.row
		.col-sm-2
			== render 'sensors/blocks/sensor_title'

		.col-sm-4
			br
			br

			.panel.panel-default
				.panel-heading
					.row
						.col-sm-12
							span = link_to "Редактировать", @sensor
				.panel-body
					.row
						.col-sm-12
							= form_for @sensor do |f|
								.row
									.col-sm-12
										-if user_signed_in?
        									-if current_user.has_role? :admin or current_user.has_role? :moderator
													h5 Номер
													= f.text_field :number, class: 'form-control', style: 'width: 100%;'
													br
										h5 Коментарий
										= f.text_area :remark, class: 'form-control', style: 'width: 100%;'
										br
										. align="right" = f.submit "Внести", class: 'btn btn-default'

src/app/views/sensors/ok_sensor_filter.slim
.container-fluid
    .row
        .col-sm-2
			== render 'sensors/add/ok_title'
		.col-sm-10
			br
			br
			== render 'sensors'

src/app/views/sensors/search.html.slim
.container-fluid
    .row
        .col-sm-2
			== render 'sensors/blocks/search_title'
		.col-sm-10
			br
			br
			== render 'search'

src/app/views/sensors/set_check_by_pm.html.slim
.col-sm-2
    == render 'sensors/blocks/sensor_title'
.col-sm-5
    br
    br

    / 4.Проверка по ПМ
    .check_by_pm_container.panel {
    data-return = @sensor.cp_result
    data-status = @sensor.check_by_pm }
        .panel-heading
            .row
                .col-sm-12
                    span = link_to "#{@sensor_cp_title[0]}", @sensor
        #check_by_pm_show.panel-body
            .row
                .col-sm-12
                    == render 'check_by_pm_form'

src/app/views/sensors/set_psi.html.slim
.col-sm-2
	== render 'sensors/blocks/sensor_title'
.col-sm-5
	br
	br

	/ 4.ПСИ
	.psi_container.panel {
	data-return = @sensor.ps_result
	data-status = @sensor.psi }
		.panel-heading
			.row
				.col-sm-12
					span = link_to "#{@sensor_ps_title[0]}", @sensor
		#psi_show.panel-body
			.row
				.col-sm-12 = render 'psi_form'

src/app/views/sensors/show.html.slim
.container-fluid
	.row
		.col-sm-2
			== render 'sensors/blocks/sensor_title'

		.col-sm-10
			br
			br
			== render 'sensors/show'

src/app/views/sensors/show_check_for_resistance_to_sinusoidal_vibration.html.slim
.col-sm-2
	== render 'sensors/blocks/sensor_title'
.col-sm-5
	br
	br
	/ 3.Проверка на устойчивость к синусоидальной вибрации
	.check_for_resistance_to_sinusoidal_vibration_container.panel {
	data-return = @sensor.cf_result
	data-status = @sensor.check_for_resistance_to_sinusoidal_vibration }
		.panel-heading
			.row
				.col-sm-11
					span = link_to "#{@sensor_cf_title[0]}", @sensor
				.col-sm-1
					- if user_signed_in?
						- if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :alignment or current_user.has_role? :adjustment
							= link_to content_tag('span', '', class: 'fa fa-pencil fa-1g', data: { toggle: 'tooltip' }, title: 'Редактировать'), set_check_for_resistance_to_sinusoidal_vibration_sensors_path(id: @sensor.id)
		.panel-body id = "check_for_resistance_to_sinusoidal_vibration_show"
			.row
				.col-sm-12 = render 'check_for_resistance_to_sinusoidal_vibration_show'