src/config/routes.rb
Rails.application.routes.draw do

    # Анализ основных параметров резонатора
    resources :resonators_analyzes do

        get :chart_1_1, on: :collection
        get :chart_1_2, on: :collection
        get :chart_1_3, on: :collection
        get :chart_1_4, on: :collection
        get :chart_1_5, on: :collection

        get :chart_3_1, on: :collection
        get :chart_3_2, on: :collection
        get :chart_3_3, on: :collection
        get :chart_3_4, on: :collection
        get :chart_3_5, on: :collection

        get :chart_5_0, on: :collection
        get :chart_7_0, on: :collection
        get :chart_9_0, on: :collection
        get :chart_11_0, on: :collection

        get :chart_13_0, on: :collection
        get :chart_15_0, on: :collection
        get :chart_17_0, on: :collection
        get :chart_19_0, on: :collection
        get :chart_21_0, on: :collection
        get :chart_23_0, on: :collection
        get :chart_25_0, on: :collection
        get :chart_27_0, on: :collection

    end


    # Анализ брака и отказов
    resources :bad_analyzes do

        # Общая статистика по браку
        get :bad_total, on: :collection

        # Брак на посту ЭВО
        get :bad_evo, on: :collection

        # Брак после ЭВО
        get :bad_after_evo, on: :collection

        # Брак по стадиям производства
        get :bad_stage, on: :collection

        # Общая статистика по отказам
        get :return_total, on: :collection

        # Отказы на посту ЭВО
        get :return_evo, on: :collection

        # Отказы после ЭВО
        get :return_after_evo, on: :collection

        # Отказы по стадиям производства
        get :return_stage, on: :collection

    end

    resources :resonators do

        # Извлечение комплектующих
        get :pull_out_cathode, on: :collection
        get :pull_out_leg, on: :collection
        get :pull_out_fmirror, on: :collection
        get :pull_out_pmirror_1, on: :collection
        get :pull_out_pmirror_2, on: :collection
        get :pull_out_smirror, on: :collection

		get :set_alignment, on: :collection
		get :show_alignment, on: :collection

        get :set_evo, on: :collection
        get :show_evo, on: :collection

        get :set_thermostabilization, on: :collection
        get :show_thermostabilization, on: :collection

        get :set_cold_resistance, on: :collection
        get :show_cold_resistance, on: :collection

        get :set_running_in, on: :collection
        get :show_running_in, on: :collection

        get :set_sealing, on: :collection
        get :show_sealing, on: :collection

        get :set_heat_treatment_in_an_argon_chamber, on: :collection
        get :show_heat_treatment_in_an_argon_chamber, on: :collection

        get :set_varnish_coating, on: :collection
        get :show_varnish_coating, on: :collection

        get :set_metallization_of_mirrors, on: :collection
        get :show_metallization_of_mirrors, on: :collection

        get :set_tinning_mirrors, on: :collection
        get :show_tinning_mirrors, on: :collection

        get :set_test3, on: :collection
        get :show_test3, on: :collection

        get :set_test9, on: :collection
        get :show_test9, on: :collection

        get :set_test10, on: :collection
        get :show_test10, on: :collection

        get :set_control, on: :collection
        get :show_control, on: :collection

        get :search, on: :collection

        # Возврат из не годных
        get :roll_back_bad, on: :collection

    end

    resources :bad_resonators

    resources :sensors do

        # 1
        get :set_align_prisms_and_fpu, on: :collection
        get :show_align_prisms_and_fpu, on: :collection

        # 2
        get :set_checking_the_build_quality_in_screens, on: :collection
        get :show_checking_the_build_quality_in_screens, on: :collection

        # 3
        get :set_check_for_resistance_to_sinusoidal_vibration, on: :collection
        get :show_check_for_resistance_to_sinusoidal_vibration, on: :collection

        # 4
        get :set_check_by_pm, on: :collection
        get :show_check_by_pm, on: :collection

        # 5
        get :set_psi, on: :collection
        get :show_psi, on: :collection

        get :search, on: :collection

        get :ok_sensor_filter, on: :collection

        # Возврат из не годных
        get :roll_back_bad, on: :collection
    end

    resources :bad_sensors

    resources :mirrors do
        get :search, on: :collection
    end

    resources :legs do
        get :search, on: :collection
    end

    resources :cathodes do
        get :search, on: :collection
    end

    devise_for :users

    root "resonators#index"
end

src/app/models/mirror.rb
class Mirror < ApplicationRecord
	resourcify
	# presence - пустое
	# uniqueness - уникально
	validates :number_of_substrate, presence: {message: "Введите номер подложки!"}
	validates :date_of_manufacture_of_the_substrate, presence: {message: "Введите дату изготовления!"}
	#validates :date_of_deposition, presence: {message: "Введите дату напыления!"}
	#validates :pa_phase_anisotropy, presence: {message: "Введите информацию о фазовой анизотропии!"}

	# уникально ли сочетание :number_of_substrate, :mirror_type, :date_of_manufacture_of_the_substrate ?
	validates :number_of_substrate, uniqueness: { scope: [:mirror_type, :date_of_manufacture_of_the_substrate], message: "Такая запись уже существует!"}

end

src/app/controllers/mirrors_controller.rb
class MirrorsController < ApplicationController

	before_action :authenticate_user!
	skip_before_action :authenticate_user!, only:[:index, :search]

	before_action :set_step,
	only: [:new, :edit]

	before_action :mirror_list_cols, 
	only: [ :index, :new, :edit, :show, :search ]

	before_action :returns_list_cols,
	only: [ :index, :new, :edit, :search ]

	before_action :element_list_cols,
	only: [ :index, :new, :edit, :search ]

	before_action :parameter_list_cols,
	only: [ :index, :new, :edit, :search]

	before_action :set_mirror,
	only: [ :edit, :update, :destroy, :show]

    before_action :mode_list_cols,
    only: [ :new, :edit, :search]

    def search
		@search_val = params[:search_val]

		if @search_val
			case $mv_type
			when 'smirror'
				@mirrors = Mirror.where(mirror_type: "сферическое").where("number_of_substrate LIKE ?", "%#{@search_val}%")
			when 'fmirror'
				@mirrors = Mirror.where(mirror_type: "плоское").where("number_of_substrate LIKE ?", "%#{@search_val}%")
			when 'pmirror'
				@mirrors = Mirror.where(mirror_type: "пьезо").where("number_of_substrate LIKE ?", "%#{@search_val}%")
			when 'all'
				@mirrors = Mirror.where("number_of_substrate LIKE ?", "%#{@search_val}%")
			end
			@mirrors = @mirrors.page(params[:page]).per_page(20)
		end
		
    end

	def index
		# Текущий вид
		if $mv_type == nil
			$mv_type = 'all'
		end

		# Текущая страница
		if $mc_page == nil
			$mc_page = 1
		end

		if params[:page]
			$mc_page = params[:page]
		end

		if params[:view_type]
			case params[:view_type]
			when 'smirror'
				$mv_type = 'smirror'

			when 'fmirror'
				$mv_type = 'fmirror'

			when 'pmirror'
				$mv_type = 'pmirror'

			when 'all'
				$mv_type = 'all'
			end
		else
			$mv_type = 'all'
		end

		case $mv_type
		when 'smirror'
			@mirrors = Mirror.where mirror_type: 'сферическое'

		when 'fmirror'
			@mirrors = Mirror.where mirror_type: 'плоское'

		when 'pmirror'
			@mirrors = Mirror.where mirror_type: 'пьезо'

		else 'all'
			@mirrors = Mirror.all
		end

				

		@mirrors = @mirrors.order(created_at: :desc).page($mc_page).per_page(25)
				


	end

	def new
		@mirror = Mirror.new
	end

	def create
		@mirror = Mirror.new(mirror_params)
		if @mirror.save
			redirect_to mirrors_path,
			notice: "Добавлена запись #{@mirror.number_of_substrate}"
		else
			redirect_to new_mirror_path,
			notice: @mirror.errors.first[1]
		end
	end

	def edit
	end

	def update
		if @mirror.update(mirror_params)
			redirect_to mirrors_path,
            notice: "Запись #{@mirror.number_of_substrate} изменена"
		else
			redirect_to edit_mirror_path,
			notice: @mirror.errors.first[1]
		end
	end

	def destroy
		if @mirror.mirror_type == "Плоское"
			del_fmirror_from_resonator(@mirror.resonator_id)
		end

		if @mirror.mirror_type == "Пьезо"
			del_pmirror_from_resonator(@mirror.resonator_id)
		end

		if @mirror.mirror_type == "Сферическое"
			del_smirror_from_resonator(@mirror.resonator_id)
		end

		if @mirror.destroy
			redirect_to mirrors_path,
            notice: "Удалена запись #{@mirror.number_of_substrate}"
		else
			redirect_to mirrors_path,
            notice: "Не удалось удалить запись #{@mirror.number_of_substrate}"
		end
	end

	private

		def set_mirror
			@mirror = Mirror.find(params[:id])
		end

		def del_fmirror_from_resonator(id)
			if resonator_id = @mirror.resonator_id
				resonator = Resonator.find(resonator_id)
				resonator.update fmirror_id: nil
			end
		end


		def del_pmirror_from_resonator(id)
			if resonator_id = @mirror.resonator_id
				resonator = Resonator.find(resonator_id)
				if resonator.pmirror_1_id == @mirror.id
					resonator.update pmirror_1_id: nil
				else
					resonator.update pmirror_2_id: nil
				end
			end
		end


		def del_smirror_from_resonator(id)
			if resonator_id = @mirror.resonator_id
				resonator = Resonator.find(resonator_id)
				resonator.update smirror_id: nil
			end
		end

		def mirror_params
			params.require(:mirror).permit(
				
				:number_of_substrate,
				:mirror_type,
				:date_of_manufacture_of_the_substrate,
				:name_of_polisher,
				:roughness_of_the_substrate,
				:radius_of_curvature_is_nominal,
				:radius_of_curvature_is_actual,
				:date_of_measurement_of_the_radius_of_curvature,
				:result_of_polishing,
				:description_of_appearance_substrate,
				:manufacturer,
				:date_of_deposition,
				:spray_installation,
				:appearance,
				:description_of_appearance,
				:date_control,
				:tl_total_losses,
				:tl_measurement,
				:tl_date_of_measurement,
				:ci_coefficient_of_integral_scattering,
				:ci_measurement,
				:ci_date_of_measurement,
				:pa_phase_anisotropy,
				:pa_ci_date_of_measurement,
				:tr_transmittance,
				:tr_date_of_measurement,
				:date_of_transfer_to_the_assembly_in_the_resonator,
				:return,
				:return_date,
				:reason_for_return,
				:for_the_return_list,
				:deviations,
				:number_of_assemblies,
				:resonator_id,
				:date_of_installation_in_the_resonator)
		end
end

src/app/helpers/mirrors_helper.rb
module MirrorsHelper
end

src/app/views/mirrors/_form.html.slim
= form_for @mirror do |f|
    table.table-condensed

        -if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :substrate or current_user.has_role? :mirror

            tr
                td colspan=2 
                    legend style="font-size: 16px; text-align: center;" Подложка

            / Номер подложки
            tr
                td = @mirror_title[0]
                td = f.text_field :number_of_substrate, class: 'form-control'
            
            / Тип
            tr
                td = @mirror_title[1]
                td = f.select :mirror_type, [["Сферическое"],["Плоское"],["Пьезо"]], {}, {class: 'select2_nosearch form-control'}
            
            / Дата изготовления подложки
            tr
                td = @mirror_title[2]
                td = f.date_select :date_of_manufacture_of_the_substrate, {include_blank: true}
            
            / ФИО полировщика
            tr
                td = @mirror_title[3]
                td = f.text_field :name_of_polisher, class: 'form-control'
            
            / Шероховатость подложки
            tr
                td = @mirror_title[4]
                td = f.number_field :roughness_of_the_substrate, step: @step, class: 'form-control'
            
            / Радиус кривизны номинальный, мм
            tr
                td = @mirror_title[5]
                td = f.select :radius_of_curvature_is_nominal, @radius_title, {}, {id: 'radius_of_curvature_is_nominal_field', class: 'select2_nosearch form-control'}
            
            / Радиус кривизны фактический, мм
            tr
                td = @mirror_title[6]
                td = f.number_field :radius_of_curvature_is_actual, step: @step, class: 'form-control'

            / Дата измерения радиуса кривизны
            tr
                td = @mirror_title[7]
                td = f.date_select :date_of_measurement_of_the_radius_of_curvature, {include_blank: true}

            
            / Результат полировки
            tr
                td = @mirror_title[8]
                td = f.select :result_of_polishing, [['Годен'],['Не годен']], {}, {class: 'select2_nosearch form-control'}
            
            / Описание внешнего вида 
            tr
                td = @mirror_title[9]
                td = f.text_field :description_of_appearance_substrate, class: 'form-control'

            tr
                td
                    p

        -if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :mirror
        
            tr
                td colspan=2 
                    legend style="font-size: 16px; text-align: center;" align="center" Зеркало
            / Изготовитель
            tr
                td = @mirror_title[10]
                td = f.select :manufacturer, @mode_list, {}, {class: 'select2_nosearch form-control'}

            / Дата напыления
            tr
                td = @mirror_title[11]
                td = f.date_select :date_of_deposition, {include_blank: true}


            / Напылительная установка
            tr
                td = @mirror_title[12]
                td = f.select :spray_installation, @spray_installation_title, {}, {class: 'select2_nosearch form-control'}

            
            / Внешний вид 
            tr
                td = @mirror_title[13]
                td = f.select :appearance, [['Годен'],['Не годен']], {},{class: 'select2_nosearch form-control'}

            / Описание внешнего вида
            tr
                td = @mirror_title[14]
                td = f.text_area :description_of_appearance, class: 'form-control'
                
            / Дата контроля внешнего вида
            tr
                td = @mirror_title[15]
                td = f.date_select :date_control, {include_blank: true}

            /-------------------------------------------------------------------------------------------
            tr
                td colspan=2
                    hr
            
            / Суммарные потери
            tr  
                td = @mirror_title[16]
                td = f.number_field :tl_total_losses, step: @step, class: 'form-control'
            
            / Тип измерения
            tr  
                td = @mirror_title[17]
                td = f.select :tl_measurement, [ ['Групповое'],['Индивидуальное'] ], {}, {class: 'select2_nosearch form-control'}
            
            / Дата измерения
            tr  
                td = @mirror_title[18]
                td = f.date_select :tl_date_of_measurement, {include_blank: true}
            
            /-------------------------------------------------------------------------------------------
            tr
                td colspan=2
                    hr

            / Коэффициент интегрального рассеяния, ppm
            tr  
                td = @mirror_title[19]
                td = f.number_field :ci_coefficient_of_integral_scattering, step: @step, class: 'form-control'
            
            / Тип измерения
            tr  
                td = @mirror_title[20]
                td = f.select :ci_measurement, [ ['Групповое'],['Индивидуальное'] ], {}, {class: 'select2_nosearch form-control'}
            
            / Дата измерения
            tr  
                td = @mirror_title[21]
                td = f.date_select :ci_date_of_measurement, {include_blank: true}

            /-------------------------------------------------------------------------------------------
            tr
                td colspan=2
                    hr
            
            / Фазовая анизотропия
            tr  
                td = @mirror_title[22]
                td = f.number_field :pa_phase_anisotropy, step: @step, class: 'form-control'

            / Дата измерения
            tr  
                td = @mirror_title[23]
                td = f.date_select :pa_ci_date_of_measurement, {include_blank: true}

            /-------------------------------------------------------------------------------------------
            tr
                td colspan=2
                    hr
            
            / Коэффициент пропускания
            tr  
                td = @mirror_title[24]
                td = f.number_field :tr_transmittance, step: @step, class: 'form-control'
            
            / Дата измерения
            tr  
                td = @mirror_title[25]
                td = f.date_select :tr_date_of_measurement, {include_blank: true}

            /-------------------------------------------------------------------------------------------
            tr
                td colspan=2
                    hr
            
            tr  
                td = @mirror_title[26]
                td = f.date_select :date_of_transfer_to_the_assembly_in_the_resonator, {include_blank: true}

            /-------------------------------------------------------------------------------------------
            tr
                td colspan=2
                    hr


            / Возврат
            tr
                td = @mirror_title[27]
                td = f.select :return, [["Нет"],["Да"]], {}, {id: 'return_field', class: 'select2_nosearch form-control'}
            
            / Дата возврата
            tr
                td = @mirror_title[28]
                td = f.date_select(:return_date, {}, {id: 'return_date_field', disabled: true})
            
            / Причина возврата
            tr
                td = @mirror_title[29]
                td = f.select :reason_for_return, @return_list_title, {}, {id: 'reason_for_return_field', class: 'select2_nosearch form-control', disabled: true}
                td

                    div.element_list data-toggle="tooltip" data-placement="right" title="Выберите элемент"
                        = f.select :for_the_return_list, @element_list_title, {}, { id: 'element_list_field', class: 'select2_nosearch form-control', disabled: true, style: 'width: 200px;'}
                

                    div.parameter_list data-toggle="tooltip" data-placement="right" title="Выберите параметр"
                        = f.select :for_the_return_list, @parametr_list_title, {}, { id: 'parameter_list_field', class: 'select2_nosearch form-control', disabled: true, style: 'width: 300px;'}
                
                    div.other_list data-toggle="tooltip" data-placement="right" title="Введите причину возврата"
                        = f.text_field :for_the_return_list, { id: 'other_list_field', class: 'form-control', disabled: true, style: 'width: 300px;'}

            /-------------------------------------------------------------------------------------------
            tr
                td colspan=2
                    hr
            
            / Отклонения (по картам отклонений)
            tr
                td = @mirror_title[30]
                td = f.text_field :deviations, class: 'form-control'

            /-------------------------------------------------------------------------------------------
            tr
                td colspan=2
                    hr

        tr
            td colspan=2 align="center" = f.submit "Внести", class: 'btn btn-default'

src/app/views/mirrors/_mirrors.html.slim
. align="left" = will_paginate @mirrors, previous_label: "<", next_label: ">"

table.table.table-condensed style="width: 90%" align="center"
	thead
		tr
			th.center = @mirror_title[0]
			th.center = @mirror_title[2]
			th.center = @mirror_title[1]
			th.center = @mirror_title[11]
			th.center = @mirror_title[10]
			th.center = @mirror_title[22]
			th.center = @mirror_title[33]
			th.center = @mirror_title[32]
			th.center = @mirror_title[34]
			th.center = @mirror_title[30]
			
			th colspan=3

	tbody
		- @mirrors.each do |mirror|
			- @mrr_title = ""

			tr
				td.center = mirror.number_of_substrate
				td.center = mirror.date_of_manufacture_of_the_substrate
				td.center = mirror.mirror_type
				td.center = mirror.date_of_deposition
				td.center = mirror.manufacturer
				td.center = mirror.pa_phase_anisotropy
				td.center = mirror.date_of_installation_in_the_resonator
				td.center
					- if mirror.resonator_id?
                        = link_to "#{Resonator.find(mirror.resonator_id).number}", resonators_path
            	- if mirror.result_of_polishing == 'Не годен' or mirror.appearance == 'Не годен' or mirror.reason_for_return?
            		td.center.back_error Не годно
    			-else
    				td.center.success Годно

				td.center data-toggle="tooltip" data-placement="bottom" title="#{mirror.deviations}"
    				- if mirror.deviations?
    					= link_to content_tag('span', '', class: 'fa fa-file-o'),mirror_path(mirror) + '#deviations', class: 'action'

				td.center = link_to content_tag('span', '', class: 'fa fa-circle-o'), mirror_path(mirror), class: 'action'
				-if user_signed_in?
					-if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :mirror
						td.center = link_to content_tag('span', '', class: 'fa fa-pencil'), edit_mirror_path(mirror), class: 'action'
				
				-if user_signed_in?
					-if current_user.has_role? :admin or current_user.has_role? :moderator
						td.center = link_to content_tag('span', '', class: 'fa fa-trash'), mirror, class: 'action', data: {confirm: "Вы хотите удалить зеркало №#{mirror.number_of_substrate}"}, method: :delete

src/app/views/mirrors/edit.html.slim
div.container-fluid
    p.sys_error
        = notice
    div.row
        div.col-sm-1
			h4 = "Редактировать зеркало #{@mirror.number_of_substrate}"
			= link_to "Назад", mirrors_path, class: 'btn btn-default'

        div.col-sm-11
            = render 'form'

src/app/views/mirrors/index.html.slim
div.container-fluid
    p.sys_success
        = notice
    div.row
        div.col-sm-1
            h4 Подложки/Зеркала
			-if user_signed_in?
				-if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :substrate or current_user.has_role? :mirror
					= link_to "Внести", new_mirror_path, class: 'btn btn-default'
            hr
            = link_to "Сферическое", mirrors_path(view_type: 'smirror', page: 1)
            br
            = link_to "Плоское", mirrors_path(view_type: 'fmirror', page: 1)
            br
            = link_to "Пьезо", mirrors_path(view_type: 'pmirror', page: 1)
            br
            = link_to "Все", mirrors_path(view_type: 'all', page: 1)

            hr

            = form_tag('mirrors/search', method: 'get', id: 'mirror_search_form') do
                table
                    tr
                        td = text_field_tag :search_val, '', class: 'form-control'
                        td 
                            .btn.fa.fa-search onclick="$('#mirror_search_form').submit()" = submit_tag "", style: 'display: none;'

        div.col-sm-11
            = render 'mirrors'

src/app/views/mirrors/new.html.slim
div.container-fluid
    p.sys_error
        = notice
    div.row
        div.col-sm-1
			h4 = "Внести зеркало #{@mirror.number_of_substrate}"
			= link_to "Назад", mirrors_path, class: 'btn btn-default'

        div.col-sm-11
            = render 'form'

src/app/views/mirrors/search.html.slim
div.container-fluid
    p.sys_success
        = notice
    div.row
        div.col-sm-1
			h4 Резонаторы
			= link_to "Назад", mirrors_path, class: 'btn btn-default'

            hr

			span ="Результат поиска по #{@search_val}"
		div.col-sm-11
			= render 'mirrors'

src/app/views/mirrors/show.html.slim
div.col-sm-2
	h4 = "Зеркало #{@mirror.number_of_substrate}"
	= link_to "Назад", mirrors_path, class: 'btn btn-default'

div.col-sm-10
	table.table-condensed
		tr
			td = @mirror_title[0]
			td = @mirror.number_of_substrate
		tr
			td = @mirror_title[1]
			td = @mirror.mirror_type
		tr
			td = @mirror_title[2]
			td = @mirror.date_of_manufacture_of_the_substrate
		tr
			td = @mirror_title[3]
			td = @mirror.name_of_polisher
		tr
			td = @mirror_title[4]
			td = @mirror.roughness_of_the_substrate
		tr
			td = @mirror_title[5]
			td = @mirror.radius_of_curvature_is_nominal
		tr
			td = @mirror_title[6]
			td = @mirror.radius_of_curvature_is_actual
		tr
			td = @mirror_title[7]
			td = @mirror.date_of_measurement_of_the_radius_of_curvature
		tr
			td = @mirror_title[8]
			td = @mirror.result_of_polishing
		tr
			td = @mirror_title[9]
			td = @mirror.description_of_appearance_substrate

		tr
			td colspan=2
				hr
		tr
			td = @mirror_title[10]
			td = @mirror.manufacturer
		tr
			td = @mirror_title[11]
			td = @mirror.date_of_deposition
		tr
			td = @mirror_title[12]
			td = @mirror.spray_installation
		tr
			td = @mirror_title[13]
			td = @mirror.appearance
		tr
			td = @mirror_title[14]
			td = @mirror.description_of_appearance

		tr
			td = @mirror_title[15]
			td = @mirror.date_control

		tr
			td colspan=2
				hr
		tr
			td = @mirror_title[16]
			td = @mirror.tl_total_losses
		tr
			td = @mirror_title[17]
			td = @mirror.tl_measurement
		tr
			td = @mirror_title[18]
			td = @mirror.tl_date_of_measurement

		tr
			td colspan=2
				hr

		tr
			td = @mirror_title[19]
			td = @mirror.ci_coefficient_of_integral_scattering
		tr
			td = @mirror_title[20]
			td = @mirror.ci_measurement
		tr
			td = @mirror_title[21]
			td = @mirror.ci_date_of_measurement

		tr
			td colspan=2
				hr

		tr
			td = @mirror_title[22]
			td = @mirror.pa_phase_anisotropy
		tr
			td = @mirror_title[23]
			td = @mirror.pa_ci_date_of_measurement

		tr
			td colspan=2
				hr

		tr
			td = @mirror_title[24]
			td = @mirror.tr_transmittance
		tr
			td = @mirror_title[25]
			td = @mirror.tr_date_of_measurement

		tr
			td colspan=2
				hr
		tr
			td = @mirror_title[26]
			td = @mirror.date_of_transfer_to_the_assembly_in_the_resonator
		tr
			td colspan=2
				hr
		tr
			td = @mirror_title[27]
			td = @mirror.return
		tr
			td = @mirror_title[28]
			td = @mirror.return_date
		tr
			td = @mirror_title[29]
			td
				-if @mirror.reason_for_return?
					= "#{@mirror.reason_for_return} (#{@mirror.for_the_return_list})"

		tr
			td colspan=2
				hr

		tr
			td = @mirror_title[30]
			td = @mirror.deviations


    	- if @mirror.resonator_id?
            tr
                td colspan=2
                    hr
            tr
                td = @mirror_title[32]
                td = link_to "#{Resonator.find(@mirror.resonator_id).number}", resonators_path
            tr
                td = @mirror_title[33]
                td = @mirror.date_of_installation_in_the_resonator
        tr
        	td = @mirror_title[31]
        	td = @mirror.number_of_assemblies