src/config/routes.rb
Rails.application.routes.draw do

    # Анализ основных параметров резонатора
    resources :resonators_analyzes do

        get :chart_1_1, on: :collection
        get :chart_1_2, on: :collection
        get :chart_1_3, on: :collection
        get :chart_1_4, on: :collection
        get :chart_1_5, on: :collection

        get :chart_3_1, on: :collection
        get :chart_3_2, on: :collection
        get :chart_3_3, on: :collection
        get :chart_3_4, on: :collection
        get :chart_3_5, on: :collection

        get :chart_5_0, on: :collection
        get :chart_7_0, on: :collection
        get :chart_9_0, on: :collection
        get :chart_11_0, on: :collection

        get :chart_13_0, on: :collection
        get :chart_15_0, on: :collection
        get :chart_17_0, on: :collection
        get :chart_19_0, on: :collection
        get :chart_21_0, on: :collection
        get :chart_23_0, on: :collection
        get :chart_25_0, on: :collection
        get :chart_27_0, on: :collection

    end


    # Анализ брака и отказов
    resources :bad_analyzes do

        # Общая статистика по браку
        get :bad_total, on: :collection

        # Брак на посту ЭВО
        get :bad_evo, on: :collection

        # Брак после ЭВО
        get :bad_after_evo, on: :collection

        # Брак по стадиям производства
        get :bad_stage, on: :collection

        # Общая статистика по отказам
        get :return_total, on: :collection

        # Отказы на посту ЭВО
        get :return_evo, on: :collection

        # Отказы после ЭВО
        get :return_after_evo, on: :collection

        # Отказы по стадиям производства
        get :return_stage, on: :collection

    end

    resources :resonators do

        # Извлечение комплектующих
        get :pull_out_cathode, on: :collection
        get :pull_out_leg, on: :collection
        get :pull_out_fmirror, on: :collection
        get :pull_out_pmirror_1, on: :collection
        get :pull_out_pmirror_2, on: :collection
        get :pull_out_smirror, on: :collection

		get :set_alignment, on: :collection
		get :show_alignment, on: :collection

        get :set_evo, on: :collection
        get :show_evo, on: :collection

        get :set_thermostabilization, on: :collection
        get :show_thermostabilization, on: :collection

        get :set_cold_resistance, on: :collection
        get :show_cold_resistance, on: :collection

        get :set_running_in, on: :collection
        get :show_running_in, on: :collection

        get :set_sealing, on: :collection
        get :show_sealing, on: :collection

        get :set_heat_treatment_in_an_argon_chamber, on: :collection
        get :show_heat_treatment_in_an_argon_chamber, on: :collection

        get :set_varnish_coating, on: :collection
        get :show_varnish_coating, on: :collection

        get :set_metallization_of_mirrors, on: :collection
        get :show_metallization_of_mirrors, on: :collection

        get :set_tinning_mirrors, on: :collection
        get :show_tinning_mirrors, on: :collection

        get :set_test3, on: :collection
        get :show_test3, on: :collection

        get :set_test9, on: :collection
        get :show_test9, on: :collection

        get :set_test10, on: :collection
        get :show_test10, on: :collection

        get :set_control, on: :collection
        get :show_control, on: :collection

        get :search, on: :collection

        # Возврат из не годных
        get :roll_back_bad, on: :collection

    end

    resources :bad_resonators

    resources :sensors do

        # 1
        get :set_align_prisms_and_fpu, on: :collection
        get :show_align_prisms_and_fpu, on: :collection

        # 2
        get :set_checking_the_build_quality_in_screens, on: :collection
        get :show_checking_the_build_quality_in_screens, on: :collection

        # 3
        get :set_check_for_resistance_to_sinusoidal_vibration, on: :collection
        get :show_check_for_resistance_to_sinusoidal_vibration, on: :collection

        # 4
        get :set_check_by_pm, on: :collection
        get :show_check_by_pm, on: :collection

        # 5
        get :set_psi, on: :collection
        get :show_psi, on: :collection

        get :search, on: :collection

        get :ok_sensor_filter, on: :collection

        # Возврат из не годных
        get :roll_back_bad, on: :collection
    end

    resources :bad_sensors

    resources :mirrors do
        get :search, on: :collection
    end

    resources :legs do
        get :search, on: :collection
    end

    resources :cathodes do
        get :search, on: :collection
    end

    devise_for :users

    root "resonators#index"
end

src/app/models/leg.rb
class Leg < ApplicationRecord
	resourcify
	# presence - пустое
	# uniqueness - уникально
	validates :disk_number, presence: {message: "Введите номер диска!"}
	validates :ds_date_of_manufacture, presence: {message: "Введите дату изготовления!"}

	# уникально ли сочетание :disk_number и :ds_date_of_manufacture ?
	validates :disk_number, uniqueness: { scope: :ds_date_of_manufacture, message: "Такая запись уже существует!"}

	mount_uploader :xray_file, XRayFileUploader
end

src/app/controllers/legs_controller.rb
class LegsController < ApplicationController

    before_action :authenticate_user!
    skip_before_action :authenticate_user!, only:[:index, :search]

    before_action :set_step,
    only: [:new, :edit, :search]

    before_action :leg_list_cols, 
    only: [ :index, :new, :edit, :show, :search ]

    before_action :returns_list_cols,
    only: [ :index, :new, :edit, :search ]

    before_action :element_list_cols,
    only: [ :index, :new, :edit, :search ]

    before_action :parameter_list_cols,
    only: [ :index, :new, :edit, :search ]

    before_action :set_leg,
    only: [ :edit, :update, :destroy, :show]

    before_action :mode_list_cols,
    only: [ :new, :edit, :search]

    def index
        # Текущая страница
        if $lc_page == nil
            $lc_page = 1
        end

        if params[:page]
            $lc_page = params[:page]
        end

        @legs = Leg.order(disk_number: :desc).page($lc_page).per_page(25)
    end

    def new
        @leg = Leg.new
    end

    def search
        @search_val = params[:search_val]
        if @search_val
            @legs = Leg.where("disk_number LIKE ?", "%#{@search_val}%").order(disk_number: :desc).page(params[:page]).per_page(25)
        end
    end

    def create
        @leg = Leg.new(leg_params)
        @leg.xray_file = params[:file]
        if @leg.save
            redirect_to legs_path,
            notice: "Добавлена запись #{@leg.disk_number}"
        else
            redirect_to new_leg_path,
            notice: @leg.errors.first[1]
        end
    end

    def edit
    end

    def update
        if @leg.update(leg_params)
            redirect_to legs_path,
            notice: "Запись #{@leg.disk_number} изменена"
        else
            redirect_to edit_leg_path,
            notice: @leg.errors.first[1]
        end
    end

    def show
    end

    def destroy
        del_leg_from_resonator(@leg.resonator_id)
        if @leg.destroy
            redirect_to legs_path,
            notice: "Удалена запись #{@leg.disk_number}"
        else
            redirect_to legs_path,
            notice: "Не удалось удалить запись #{@leg.disk_number}"
        end
    end

    private

        def set_leg
            @leg = Leg.find(params[:id])
        end

        def del_leg_from_resonator(id)
            if resonator_id = @leg.resonator_id
                resonator = Resonator.find(resonator_id)
                resonator.update leg_id: nil
            end
        end

        def leg_params
            params.require(:leg).permit(
                :disk_number,
                :ds_date_of_manufacture,
                :ds_the_nonplaneity_of_the_disc_n,
                :ds_the_discontinuity_of_the_disk_n,
                :ds_appearance_ok,
                :ds_description_of_appearance_ok,
                :ds_date_control_ok,
                :sd_soldering_date,
                :sd_non_flatness_of_the_foot_n,
                :sd_the_non_flatness_of_the_foot_n,
                :sd_germ_checking_for_leaks,
                :sd_germ_date_control,
                :sd_appearance_ok,
                :sd_description_of_appearance_ok,
                :sd_date_control_ok,
                :date_of_transfer_to_the_assembly_in_the_resonator,
                :return_date,
                :reason_for_return,
                :for_the_return_list,
                :deviations,
                :number_of_assemblies,
                :resonator_id,
                :xray_file)
        end
end

src/app/helpers/legs_helper.rb
module LegsHelper
end

src/app/views/legs/_form.html.slim
= form_for @leg do |f|
    table.table-condensed
        / Номер диска
        tr
            td = @leg_title[0]
            td = f.text_field :disk_number, class: 'form-control'
        
        / Дата изготовления
        tr
            td = @leg_title[1]
            td = f.date_select :ds_date_of_manufacture, {include_blank: true}
        
        / Неплоскостность диска N
        tr
            td = @leg_title[2]
            td = f.number_field :ds_the_nonplaneity_of_the_disc_n, step: @step, class: 'form-control'
        
        / Неплоскостность диска ΔN
        tr
            td = @leg_title[3]
            td = f.number_field :ds_the_discontinuity_of_the_disk_n, step: @step, class: 'form-control'
        
        / Внешний вид оптического контакта
        tr
            td = @leg_title[4]
            td = f.select :ds_appearance_ok, [["Годен"],["Не годен"]], {}, {class: 'select2_nosearch form-control'}
        
        / Описание внешнего вида
        tr
            td = @leg_title[5]
            td = f.text_area :ds_description_of_appearance_ok, class: 'form-control'
        
        / Дата контроля
        tr
            td = @leg_title[6]
            td = f.date_select :ds_date_control_ok, {include_blank: true}
        

        / ----------------------------------------------------------------------------------------------
        tr
            td colspan="3"
                hr

        / Дата пайки
        tr
            td = @leg_title[7]
            td = f.date_select :sd_soldering_date, {include_blank: true}
        
        / Неплоскостность ножки N
        tr
            td = @leg_title[8]
            td = f.number_field :sd_non_flatness_of_the_foot_n, step: @step, class: 'form-control'
        
        / Неплоскостность ножки ΔN
        tr
            td = @leg_title[9]
            td = f.number_field :sd_the_non_flatness_of_the_foot_n, step: @step, class: 'form-control'
        
        / Контроль герметичности
        tr
            td = @leg_title[10]
            td = f.select :sd_germ_checking_for_leaks, [["Годен"],["Не годен"]], {}, {class: 'select2_nosearch form-control'}
        
        / Дата контроля
        tr
            td = @leg_title[11]
            td = f.date_select :sd_germ_date_control, {include_blank: true}
        
        / Внешний вид оптического контакта
        tr
            td = @leg_title[12]
            td = f.select :sd_appearance_ok, [["Годен"],["Не годен"]], {}, {class: 'select2_nosearch form-control'}
        
        / Описание внешнего вида
        tr
            td = @leg_title[13]
            td = f.text_area :sd_description_of_appearance_ok, class: 'form-control'
        
        / ----------------------------------------------------------------------------------------------
        tr
            td colspan="3"
                hr

        / Дата контроля
        tr
            td = @leg_title[14]
            td = f.date_select :sd_date_control_ok, {include_blank: true}
        tr
            td = @leg_title[15]
            td = f.date_select :date_of_transfer_to_the_assembly_in_the_resonator, {include_blank: true}

        / ----------------------------------------------------------------------------------------------
        tr
            td colspan="3"
                hr
        / Возврат
        tr
            td = @leg_title[16]
            td = f.select :return, [["Нет"],["Да"]], {}, {id: 'return_field', class: 'select2_nosearch form-control'}
        
        / Дата возврата
        tr
            td = @leg_title[17]
            td = f.date_select :return_date, {}, {id: 'return_date_field', disabled: true}
        
        / Причина возврата
        tr
            td = @leg_title[18]
            td = f.select :reason_for_return, @return_list_title, {}, {id: 'reason_for_return_field', class: 'select2_nosearch form-control', disabled: true}
            td

                div.element_list data-toggle="tooltip" data-placement="right" title="Выберите элемент"
                    = f.select :for_the_return_list, @element_list_title, {}, { id: 'element_list_field', class: 'select2_nosearch form-control', disabled: true, style: 'width: 200px;'}
            

                div.parameter_list data-toggle="tooltip" data-placement="right" title="Выберите параметр"
                    = f.select :for_the_return_list, @parametr_list_title, {}, { id: 'parameter_list_field', class: 'select2_nosearch form-control', disabled: true, style: 'width: 300px;'}
            
                div.other_list data-toggle="tooltip" data-placement="right" title="Введите причину возврата"
                    = f.text_field :for_the_return_list, { id: 'other_list_field', class: 'select2_nosearch form-control', disabled: true, style: 'width: 300px;'}
                    
        / Отклонения
        tr
            td = @leg_title[19]
            td = f.text_field :deviations, class: 'form-control'

        /-------------------------------------------------------------------------------------------
        tr
            td colspan=2
                hr

        / Изображение
        tr
            td = @leg_title[25]
            td = f.file_field :xray_file



        tr
            td align="center" colspan="3" = f.submit "Внести", class: 'btn btn-default'
                

src/app/views/legs/_legs.html.slim
. align="left" = will_paginate @legs, previous_label: "<", next_label: ">"

table.table.table-condensed style="width: 90%" align="center"
	thead
		tr
			th.center = @leg_title[0]
			th.center = @leg_title[1]
			th.center = @leg_title[7]
			th.center = @leg_title[15]
			th.center = @leg_title[21]
			th.center = @leg_title[22]
			th.center = @leg_title[23]
			th.center = @leg_title[24]
			th colspan=3

	tbody
		- @legs.each do |leg|
			- @leg_title = ""

			tr
				td.center = leg.disk_number
				td.center = leg.ds_date_of_manufacture
				td.center = leg.sd_soldering_date
				td.center = leg.date_of_transfer_to_the_assembly_in_the_resonator
				
				td.center 
					- if leg.resonator_id?
                    	= link_to "#{Resonator.find(leg.resonator_id).number}", resonators_path
                        td.center = leg.date_of_installation_in_the_resonator
                    - else
                    	td
              	
              	- if leg.ds_appearance_ok == "Не годна" or leg.sd_germ_checking_for_leaks == "Не годна" or leg.sd_appearance_ok == "Не годна" or leg.reason_for_return?
    				td.center.back_error Не годна
        		-else
        			td.center.success Годна

    			td.center title="#{leg.deviations}"
    				- if leg.deviations?
    					= link_to content_tag('span', '', class: 'fa fa-file-o'),leg_path(leg) + '#deviations', class: 'action'

				td.center
	                / Изображение
	                - if leg.xray_file?
	                	= link_to content_tag('span', '', class: 'fa fa-file-image-o'), "#{leg.xray_file}"

				td = link_to content_tag('span', '', class: 'fa fa-circle-o'), leg_path(leg), class: 'action'

				-if user_signed_in?
					-if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :leg
						td = link_to content_tag('span', '', class: 'fa fa-pencil'), edit_leg_path(leg), class: 'action'

				-if user_signed_in?
					-if current_user.has_role? :admin or current_user.has_role? :moderator
						td = link_to content_tag('span', '', class: 'fa fa-trash'), leg, class: 'action', data: {confirm: "Хотите удалить ножку #{leg.disk_number}?"}, method: :delete

src/app/views/legs/edit.html.slim
div.container-fluid
    p.sys_error
        = notice
    div.row
        div.col-sm-1
			h4 = "Редактировать ножку #{@leg.disk_number}"
			= link_to "Назад", legs_path, class: 'btn btn-default'

        div.col-sm-11
            = render 'form'

src/app/views/legs/index.html.slim
div.container-fluid
    p.sys_success
        = notice
    div.row
        div.col-sm-1
			h4 Ножки
			-if user_signed_in?
				-if current_user.has_role? :admin or current_user.has_role? :moderator or current_user.has_role? :leg
					= link_to "Внести", new_leg_path, class: 'btn btn-default'

            hr

            = form_tag('legs/search', method: 'get', id: 'legs_search_form') do
                table
                    tr
                        td = text_field_tag :search_val, '', class: 'form-control'
                        td 
                            .btn.fa.fa-search onclick="$('#legs_search_form').submit()" = submit_tag nil, style: 'display: none;'

        div.col-sm-11
            = render 'legs'

src/app/views/legs/new.html.slim
div.container-fluid
    p.sys_error
        = notice
    div.row
        div.col-sm-1
			h4 = "Внести ножку"
			= link_to "Назад", legs_path, class: 'btn btn-default'

        div.col-sm-11
            = render 'form'

src/app/views/legs/search.html.slim
div.container-fluid
    p.sys_success
        = notice
    div.row
        div.col-sm-1
			h4 Ножки
			= link_to "Назад", legs_path, class: 'btn btn-default'

            hr

			span ="Результат поиска по #{@search_val}"
		div.col-sm-11
			= render 'legs'

src/app/views/legs/show.html.slim
div.container-fluid
    p.sys_error
        = notice
    div.row
        div.col-sm-1
            h4 = "Ножка #{@leg.disk_number}"
            = link_to "Назад", legs_path, class: 'btn btn-default'

        div.col-sm-11
        
            table.table-condensed
                tr
                    td = @leg_title[0]
                    td = @leg.disk_number
                tr
                    td = @leg_title[1]
                    td = @leg.ds_date_of_manufacture
                tr
                    td = @leg_title[2]
                    td = @leg.ds_the_nonplaneity_of_the_disc_n
                tr
                    td = @leg_title[3]
                    td = @leg.ds_the_discontinuity_of_the_disk_n
                tr
                    td = @leg_title[4]
                    td = @leg.ds_appearance_ok
                tr
                    td = @leg_title[5]
                    td = @leg.ds_description_of_appearance_ok
                tr
                    td = @leg_title[6]
                    td = @leg.ds_date_control_ok
                tr
                    td colspan=2
                        hr
                tr
                    td = @leg_title[7]
                    td = @leg.sd_soldering_date
                tr
                    td = @leg_title[8]
                    td = @leg.sd_non_flatness_of_the_foot_n
                tr
                    td = @leg_title[9]
                    td = @leg.sd_the_non_flatness_of_the_foot_n
                tr
                    td = @leg_title[10]
                    td = @leg.sd_germ_checking_for_leaks
                tr
                    td = @leg_title[11]
                    td = @leg.sd_germ_date_control
                tr
                    td = @leg_title[12]
                    td = @leg.sd_appearance_ok
                tr
                    td = @leg_title[13]
                    td = @leg.sd_description_of_appearance_ok

                tr
                    td colspan=2
                        hr
                
                tr
                    td = @leg_title[14]
                    td = @leg.sd_date_control_ok
                tr
                    td = @leg_title[15]
                    td = @leg.date_of_transfer_to_the_assembly_in_the_resonator

                
                tr
                    td colspan=2
                        hr


                tr
                    td
                        b = @leg_title[16]
                    td
                tr
                    td = @leg_title[17]
                    td = @leg.return_date
                tr
                    td = @leg_title[18]
                    td  
                        -if @leg.reason_for_return?
                            = "#{@leg.reason_for_return} (#{@leg.for_the_return_list})"
                
                tr
                    td colspan=2
                        hr

                tr
                    td id="deviations"
                        = @leg_title[19]
                    td = @leg.deviations


                - if @leg.resonator_id?
                    tr
                        td colspan=2
                            hr
                    tr
                        td = @leg_title[21]
                        td = link_to "#{Resonator.find(@leg.resonator_id).number}", resonators_path
                    tr
                        td = @leg_title[22]
                        td = @leg.date_of_installation_in_the_resonator
                tr
                    td = @leg_title[20]
                    td = @leg.number_of_assemblies